// ============================================================================
// EHCM Payroll Module - Comprehensive Indian Payroll Master Data & Presets
// ============================================================================

import type {
  SalaryComponentItem,
  StructureTemplate,
  SampleEmployeeSalary,
  StatutorySettingsData,
  TaxRegimeData,
} from './types';

export * from './types';

// Runtime fallback exports so browser ESM loaders never error on named import
export const SalaryComponentItem = undefined;
export const StructureTemplate = undefined;
export const SampleEmployeeSalary = undefined;
export const StatutorySettingsData = undefined;
export const TaxRegimeData = undefined;

export const MASTER_SALARY_COMPONENTS: SalaryComponentItem[] = [
  {
    id: 'comp-basic',
    code: 'BASIC',
    name: 'Basic Salary',
    type: 'EARNING',
    category: 'Basic',
    description: 'Foundational earnings component (typically 40% - 50% of CTC)',
    calculationType: 'PERCENTAGE',
    calculationValue: 50,
    calculationBase: 'CTC',
    frequency: 'MONTHLY',
    displayOrder: 1,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: true,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: true,
    isEsiApplicable: true,
    isPtApplicable: true,
    isLwfApplicable: false,
    isGratuityApplicable: true,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-hra',
    code: 'HRA',
    name: 'House Rent Allowance',
    type: 'EARNING',
    category: 'Allowance',
    description: 'House rent subsidy (50% of Basic for Metro, 40% for Non-Metro)',
    calculationType: 'PERCENTAGE',
    calculationValue: 50,
    calculationBase: 'BASIC',
    frequency: 'MONTHLY',
    displayOrder: 2,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: true,
    isPtApplicable: true,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-da',
    code: 'DA',
    name: 'Dearness Allowance',
    type: 'EARNING',
    category: 'Allowance',
    description: 'Cost-of-living allowance adjusted for inflation',
    calculationType: 'PERCENTAGE',
    calculationValue: 10,
    calculationBase: 'BASIC',
    frequency: 'MONTHLY',
    displayOrder: 3,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: true,
    isEsiApplicable: true,
    isPtApplicable: true,
    isLwfApplicable: false,
    isGratuityApplicable: true,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-conveyance',
    code: 'CONV',
    name: 'Conveyance Allowance',
    type: 'EARNING',
    category: 'Allowance',
    description: 'Fixed transport allowance for daily commute',
    calculationType: 'FIXED',
    calculationValue: 1600,
    frequency: 'MONTHLY',
    displayOrder: 4,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: true,
    isPtApplicable: true,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-med-allow',
    code: 'MED_ALLOW',
    name: 'Medical Allowance',
    type: 'EARNING',
    category: 'Allowance',
    description: 'Fixed monthly medical allowance',
    calculationType: 'FIXED',
    calculationValue: 1250,
    frequency: 'MONTHLY',
    displayOrder: 5,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: true,
    isPtApplicable: true,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-special-allow',
    code: 'SPECIAL_ALLOW',
    name: 'Special Allowance',
    type: 'EARNING',
    category: 'Balancing Figure',
    description: 'Residual balancing component to reconcile CTC with component allowances',
    calculationType: 'BALANCING',
    calculationValue: 0,
    frequency: 'MONTHLY',
    displayOrder: 6,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: true,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: true,
    isPtApplicable: true,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-ot',
    code: 'OT_ALLOW',
    name: 'Overtime Pay',
    type: 'EARNING',
    category: 'Variable',
    description: 'Overtime wages computed as (BASIC / 26 / 8) * 2 * OT_HOURS',
    calculationType: 'FORMULA',
    calculationValue: 0,
    formula: '(BASIC / 26 / 8) * 2 * (ot_hours || 0)',
    frequency: 'MONTHLY',
    displayOrder: 7,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: false,
    showOnPayslip: true,
    proRateOnLop: false,
    isPfApplicable: false,
    isEsiApplicable: true,
    isPtApplicable: true,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-bonus',
    code: 'PERF_BONUS',
    name: 'Performance Bonus',
    type: 'EARNING',
    category: 'Variable',
    description: 'Periodic incentive or KPI-based performance bonus',
    calculationType: 'MANUAL',
    calculationValue: 0,
    frequency: 'QUARTERLY',
    displayOrder: 8,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: true,
    includeInGross: true,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: false,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: true,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-pf-ee',
    code: 'PF_EE',
    name: 'Provident Fund (Employee)',
    type: 'DEDUCTION',
    category: 'Statutory',
    description: 'Statutory employee EPF contribution (12% of Basic + DA, capped at ₹1,800 or actual)',
    calculationType: 'FORMULA',
    calculationValue: 12,
    calculationBase: 'BASIC_DA',
    formula: 'MIN(BASIC, 15000) * 0.12',
    frequency: 'MONTHLY',
    displayOrder: 9,
    roundingRule: 'NEAREST_1',
    isStatutory: true,
    isSystem: true,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: false,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-esi-ee',
    code: 'ESI_EE',
    name: 'ESIC (Employee)',
    type: 'DEDUCTION',
    category: 'Statutory',
    description: 'Employees State Insurance (0.75% of Gross if Gross <= ₹21,000/mo)',
    calculationType: 'FORMULA',
    calculationValue: 0.75,
    calculationBase: 'GROSS',
    formula: 'GROSS <= 21000 ? GROSS * 0.0075 : 0',
    frequency: 'MONTHLY',
    displayOrder: 10,
    roundingRule: 'CEIL',
    isStatutory: true,
    isSystem: true,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: false,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-pt',
    code: 'PT',
    name: 'Professional Tax',
    type: 'DEDUCTION',
    category: 'Statutory',
    description: 'State statutory professional tax (e.g. Maharashtra ₹200/mo, ₹300 Feb)',
    calculationType: 'FIXED',
    calculationValue: 200,
    frequency: 'MONTHLY',
    displayOrder: 11,
    roundingRule: 'NEAREST_1',
    isStatutory: true,
    isSystem: true,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: false,
    showOnPayslip: true,
    proRateOnLop: false,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-tds',
    code: 'TDS',
    name: 'Tax Deducted at Source (TDS)',
    type: 'DEDUCTION',
    category: 'Statutory',
    description: 'Income tax deducted monthly based on annual projected taxable income',
    calculationType: 'MANUAL',
    calculationValue: 0,
    frequency: 'MONTHLY',
    displayOrder: 12,
    roundingRule: 'NEAREST_1',
    isStatutory: true,
    isSystem: true,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: false,
    showOnPayslip: true,
    proRateOnLop: false,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-lwf-ee',
    code: 'LWF_EE',
    name: 'Labour Welfare Fund (Employee)',
    type: 'DEDUCTION',
    category: 'Statutory',
    description: 'Employee share towards State Labour Welfare Fund (e.g., ₹12 in Maharashtra)',
    calculationType: 'FIXED',
    calculationValue: 12,
    frequency: 'MONTHLY',
    displayOrder: 13,
    roundingRule: 'NEAREST_1',
    isStatutory: true,
    isSystem: true,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: false,
    showOnPayslip: true,
    proRateOnLop: false,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-pf-er',
    code: 'PF_ER',
    name: 'Provident Fund (Employer)',
    type: 'EMPLOYER_CONTRIBUTION',
    category: 'Statutory',
    description: 'Employer PF (3.67% EPF + 8.33% EPS = 12% of Basic, capped at ₹1,800 or actual)',
    calculationType: 'FORMULA',
    calculationValue: 12,
    calculationBase: 'BASIC',
    formula: 'MIN(BASIC, 15000) * 0.12',
    frequency: 'MONTHLY',
    displayOrder: 14,
    roundingRule: 'NEAREST_1',
    isStatutory: true,
    isSystem: true,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-esi-er',
    code: 'ESI_ER',
    name: 'ESIC (Employer)',
    type: 'EMPLOYER_CONTRIBUTION',
    category: 'Statutory',
    description: 'Employer ESIC contribution (3.25% of Gross if Gross <= ₹21,000)',
    calculationType: 'FORMULA',
    calculationValue: 3.25,
    calculationBase: 'GROSS',
    formula: 'GROSS <= 21000 ? GROSS * 0.0325 : 0',
    frequency: 'MONTHLY',
    displayOrder: 15,
    roundingRule: 'CEIL',
    isStatutory: true,
    isSystem: true,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-gratuity',
    code: 'GRATUITY',
    name: 'Gratuity Provision',
    type: 'EMPLOYER_CONTRIBUTION',
    category: 'Statutory',
    description: 'Employer gratuity liability provision: 4.81% of Basic ((15/26)/12)',
    calculationType: 'FORMULA',
    calculationValue: 4.81,
    calculationBase: 'BASIC',
    formula: '(BASIC * 15) / 26 / 12',
    frequency: 'MONTHLY',
    displayOrder: 16,
    roundingRule: 'NEAREST_1',
    isStatutory: true,
    isSystem: false,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: true,
    showOnPayslip: false,
    proRateOnLop: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-fuel-reimb',
    code: 'FUEL_REIMB',
    name: 'Fuel & Travel Reimbursement',
    type: 'REIMBURSEMENT',
    category: 'Expense Claim',
    description: 'Tax-exempt vehicle running reimbursement against valid fuel receipts',
    calculationType: 'FIXED',
    calculationValue: 2400,
    frequency: 'MONTHLY',
    displayOrder: 17,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: false,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
  {
    id: 'comp-tel-reimb',
    code: 'TEL_REIMB',
    name: 'Telephone & Internet Reimbursement',
    type: 'REIMBURSEMENT',
    category: 'Expense Claim',
    description: 'Mobile phone & home broadband reimbursement against invoices',
    calculationType: 'FIXED',
    calculationValue: 1500,
    frequency: 'MONTHLY',
    displayOrder: 18,
    roundingRule: 'NEAREST_1',
    isStatutory: false,
    isSystem: false,
    isTaxable: false,
    includeInGross: false,
    includeInCtc: true,
    showOnPayslip: true,
    proRateOnLop: false,
    isPfApplicable: false,
    isEsiApplicable: false,
    isPtApplicable: false,
    isLwfApplicable: false,
    isGratuityApplicable: false,
    isTdsApplicable: false,
    isActive: true,
    effectiveFrom: '2025-04-01',
  },
];

// Industry Presets & Structure Templates

export const INDUSTRY_PRESET_TEMPLATES: StructureTemplate[] = [
  {
    id: 'tpl-it-tech',
    name: 'IT & Software Engineering (Standard CTC)',
    code: 'IT-ENG-CTC',
    gradeCode: 'G3',
    gradeName: 'Senior Software Engineer',
    category: 'White Collar / Tech',
    industry: 'IT',
    description: 'Designed for IT companies with 50% Basic, HRA, statutory PF, PT, and Special Allowance balancing figure.',
    balancingComponentCode: 'SPECIAL_ALLOW',
    version: 1,
    isActive: true,
    minCtc: 400000,
    maxCtc: 3000000,
    items: [
      { componentCode: 'BASIC', componentName: 'Basic Salary', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 50, calculationBase: 'CTC', order: 1 },
      { componentCode: 'HRA', componentName: 'House Rent Allowance', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 50, calculationBase: 'BASIC', order: 2 },
      { componentCode: 'CONV', componentName: 'Conveyance Allowance', type: 'EARNING', calculationType: 'FIXED', calculationValue: 1600, order: 3 },
      { componentCode: 'MED_ALLOW', componentName: 'Medical Allowance', type: 'EARNING', calculationType: 'FIXED', calculationValue: 1250, order: 4 },
      { componentCode: 'SPECIAL_ALLOW', componentName: 'Special Allowance', type: 'EARNING', calculationType: 'BALANCING', isBalancing: true, order: 5 },
      { componentCode: 'PF_EE', componentName: 'Provident Fund (Employee)', type: 'DEDUCTION', calculationType: 'FORMULA', calculationValue: 12, order: 6 },
      { componentCode: 'PT', componentName: 'Professional Tax', type: 'DEDUCTION', calculationType: 'FIXED', calculationValue: 200, order: 7 },
      { componentCode: 'PF_ER', componentName: 'Provident Fund (Employer)', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 12, order: 8 },
      { componentCode: 'GRATUITY', componentName: 'Gratuity Provision', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 4.81, order: 9 },
    ],
  },
  {
    id: 'tpl-mfg-floor',
    name: 'Manufacturing Floor (Daily Wage + OT + ESIC)',
    code: 'MFG-FLOOR-WAGE',
    gradeCode: 'L5',
    gradeName: 'Floor Technician',
    category: 'Factory / Plant Staff',
    industry: 'MANUFACTURING',
    description: 'Compliant with Factories Act, Minimum Wages Act, ESIC (Gross <= 21k), and overtime rate (2x).',
    balancingComponentCode: 'SPECIAL_ALLOW',
    version: 1,
    isActive: true,
    minCtc: 200000,
    maxCtc: 450000,
    items: [
      { componentCode: 'BASIC', componentName: 'Basic Salary', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 55, calculationBase: 'CTC', order: 1 },
      { componentCode: 'DA', componentName: 'Dearness Allowance', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 15, calculationBase: 'BASIC', order: 2 },
      { componentCode: 'HRA', componentName: 'House Rent Allowance', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 40, calculationBase: 'BASIC', order: 3 },
      { componentCode: 'SPECIAL_ALLOW', componentName: 'Special Allowance', type: 'EARNING', calculationType: 'BALANCING', isBalancing: true, order: 4 },
      { componentCode: 'PF_EE', componentName: 'Provident Fund (Employee)', type: 'DEDUCTION', calculationType: 'FORMULA', calculationValue: 12, order: 5 },
      { componentCode: 'ESI_EE', componentName: 'ESIC (Employee)', type: 'DEDUCTION', calculationType: 'FORMULA', calculationValue: 0.75, order: 6 },
      { componentCode: 'LWF_EE', componentName: 'Labour Welfare Fund', type: 'DEDUCTION', calculationType: 'FIXED', calculationValue: 12, order: 7 },
      { componentCode: 'PT', componentName: 'Professional Tax', type: 'DEDUCTION', calculationType: 'FIXED', calculationValue: 200, order: 8 },
      { componentCode: 'PF_ER', componentName: 'Provident Fund (Employer)', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 12, order: 9 },
      { componentCode: 'ESI_ER', componentName: 'ESIC (Employer)', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 3.25, order: 10 },
    ],
  },
  {
    id: 'tpl-retail-sales',
    name: 'Retail Store Associate (Incentive + Allowance)',
    code: 'RETAIL-STORE-ASSOC',
    gradeCode: 'L4',
    gradeName: 'Store Sales Associate',
    category: 'Retail / Frontline',
    industry: 'RETAIL',
    description: 'Optimized for high-turnover retail stores with lower base, statutory ESIC, and sales commission balancing.',
    balancingComponentCode: 'SPECIAL_ALLOW',
    version: 1,
    isActive: true,
    minCtc: 240000,
    maxCtc: 600000,
    items: [
      { componentCode: 'BASIC', componentName: 'Basic Salary', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 50, calculationBase: 'CTC', order: 1 },
      { componentCode: 'HRA', componentName: 'House Rent Allowance', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 40, calculationBase: 'BASIC', order: 2 },
      { componentCode: 'CONV', componentName: 'Conveyance Allowance', type: 'EARNING', calculationType: 'FIXED', calculationValue: 1600, order: 3 },
      { componentCode: 'SPECIAL_ALLOW', componentName: 'Special Allowance', type: 'EARNING', calculationType: 'BALANCING', isBalancing: true, order: 4 },
      { componentCode: 'PF_EE', componentName: 'Provident Fund (Employee)', type: 'DEDUCTION', calculationType: 'FORMULA', calculationValue: 12, order: 5 },
      { componentCode: 'ESI_EE', componentName: 'ESIC (Employee)', type: 'DEDUCTION', calculationType: 'FORMULA', calculationValue: 0.75, order: 6 },
      { componentCode: 'PT', componentName: 'Professional Tax', type: 'DEDUCTION', calculationType: 'FIXED', calculationValue: 200, order: 7 },
      { componentCode: 'PF_ER', componentName: 'Provident Fund (Employer)', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 12, order: 8 },
      { componentCode: 'ESI_ER', componentName: 'ESIC (Employer)', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 3.25, order: 9 },
    ],
  },
  {
    id: 'tpl-healthcare-nurse',
    name: 'Healthcare & Clinical Staff (Shift & Risk Allowance)',
    code: 'HEALTH-CLINICAL-NURSE',
    gradeCode: 'G4',
    gradeName: 'Registered Staff Nurse',
    category: 'Healthcare / Hospital',
    industry: 'HEALTHCARE',
    description: 'Hospital structure tailored for medical staff with night-shift, risk allowances, and statutory benefits.',
    balancingComponentCode: 'SPECIAL_ALLOW',
    version: 1,
    isActive: true,
    minCtc: 360000,
    maxCtc: 900000,
    items: [
      { componentCode: 'BASIC', componentName: 'Basic Salary', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 50, calculationBase: 'CTC', order: 1 },
      { componentCode: 'HRA', componentName: 'House Rent Allowance', type: 'EARNING', calculationType: 'PERCENTAGE', calculationValue: 40, calculationBase: 'BASIC', order: 2 },
      { componentCode: 'CONV', componentName: 'Conveyance Allowance', type: 'EARNING', calculationType: 'FIXED', calculationValue: 2000, order: 3 },
      { componentCode: 'MED_ALLOW', componentName: 'Medical Allowance', type: 'EARNING', calculationType: 'FIXED', calculationValue: 2500, order: 4 },
      { componentCode: 'SPECIAL_ALLOW', componentName: 'Special Allowance', type: 'EARNING', calculationType: 'BALANCING', isBalancing: true, order: 5 },
      { componentCode: 'PF_EE', componentName: 'Provident Fund (Employee)', type: 'DEDUCTION', calculationType: 'FORMULA', calculationValue: 12, order: 6 },
      { componentCode: 'PT', componentName: 'Professional Tax', type: 'DEDUCTION', calculationType: 'FIXED', calculationValue: 200, order: 7 },
      { componentCode: 'PF_ER', componentName: 'Provident Fund (Employer)', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 12, order: 8 },
      { componentCode: 'GRATUITY', componentName: 'Gratuity Provision', type: 'EMPLOYER_CONTRIBUTION', calculationType: 'FORMULA', calculationValue: 4.81, order: 9 },
    ],
  },
];

// Sample Employees with and without Salary Structure assigned

export const SAMPLE_EMPLOYEE_SALARIES: SampleEmployeeSalary[] = [
  {
    id: 'asgn-001',
    employeeId: 'emp-101',
    employeeCode: 'EHCM-1001',
    name: 'Sudarshan Kales',
    department: 'Engineering',
    designation: 'Staff Software Architect',
    grade: 'G1',
    templateCode: 'IT-ENG-CTC',
    templateName: 'IT & Software Engineering (Standard CTC)',
    annualCtc: 2400000,
    monthlyCtc: 200000,
    grossSalary: 191600,
    netSalary: 172800,
    effectiveFrom: '2025-04-01',
    taxRegime: 'NEW',
    status: 'ACTIVE',
    hasSalaryAssigned: true,
    complianceRuleCompliant: true,
  },
  {
    id: 'asgn-002',
    employeeId: 'emp-102',
    employeeCode: 'EHCM-1002',
    name: 'Priyanka Sharma',
    department: 'Product',
    designation: 'Senior Product Manager',
    grade: 'G2',
    templateCode: 'IT-ENG-CTC',
    templateName: 'IT & Software Engineering (Standard CTC)',
    annualCtc: 1800000,
    monthlyCtc: 150000,
    grossSalary: 143700,
    netSalary: 129500,
    effectiveFrom: '2025-04-01',
    taxRegime: 'NEW',
    status: 'ACTIVE',
    hasSalaryAssigned: true,
    complianceRuleCompliant: true,
  },
  {
    id: 'asgn-003',
    employeeId: 'emp-103',
    employeeCode: 'EHCM-1003',
    name: 'Aarav Patel',
    department: 'Operations',
    designation: 'Plant Floor Supervisor',
    grade: 'L4',
    templateCode: 'MFG-FLOOR-WAGE',
    templateName: 'Manufacturing Floor (Daily Wage + OT + ESIC)',
    annualCtc: 480000,
    monthlyCtc: 40000,
    grossSalary: 37600,
    netSalary: 34800,
    effectiveFrom: '2025-05-01',
    taxRegime: 'NEW',
    status: 'ACTIVE',
    hasSalaryAssigned: true,
    complianceRuleCompliant: true,
  },
  {
    id: 'asgn-004',
    employeeId: 'emp-104',
    employeeCode: 'EHCM-1004',
    name: 'Neha Deshmukh',
    department: 'Healthcare Operations',
    designation: 'Senior Staff Nurse',
    grade: 'G4',
    templateCode: 'HEALTH-CLINICAL-NURSE',
    templateName: 'Healthcare & Clinical Staff (Shift & Risk Allowance)',
    annualCtc: 650000,
    monthlyCtc: 54167,
    grossSalary: 51200,
    netSalary: 47400,
    effectiveFrom: '2025-06-01',
    taxRegime: 'OLD',
    status: 'ACTIVE',
    hasSalaryAssigned: true,
    complianceRuleCompliant: true,
  },
  {
    id: 'asgn-005',
    employeeId: 'emp-105',
    employeeCode: 'EHCM-1005',
    name: 'Rohan Verma',
    department: 'Retail Sales',
    designation: 'Store Lead Associate',
    grade: 'L4',
    templateCode: 'RETAIL-STORE-ASSOC',
    templateName: 'Retail Store Associate (Incentive + Allowance)',
    annualCtc: 360000,
    monthlyCtc: 30000,
    grossSalary: 28400,
    netSalary: 26200,
    effectiveFrom: '2025-04-01',
    taxRegime: 'NEW',
    status: 'ACTIVE',
    hasSalaryAssigned: true,
    complianceRuleCompliant: true,
  },
  // Unassigned Employees needing salary structure
  {
    id: 'unassigned-001',
    employeeId: 'emp-106',
    employeeCode: 'EHCM-1006',
    name: 'Kavita Joshi',
    department: 'Quality Assurance',
    designation: 'QA Automation Engineer',
    grade: 'G3',
    templateCode: '',
    templateName: 'No Template Assigned',
    annualCtc: 0,
    monthlyCtc: 0,
    grossSalary: 0,
    netSalary: 0,
    effectiveFrom: '',
    taxRegime: 'NEW',
    status: 'PENDING',
    hasSalaryAssigned: false,
    complianceRuleCompliant: false,
  },
  {
    id: 'unassigned-002',
    employeeId: 'emp-107',
    employeeCode: 'EHCM-1007',
    name: 'Vikram Singh',
    department: 'Logistics',
    designation: 'Warehouse Coordinator',
    grade: 'L5',
    templateCode: '',
    templateName: 'No Template Assigned',
    annualCtc: 0,
    monthlyCtc: 0,
    grossSalary: 0,
    netSalary: 0,
    effectiveFrom: '',
    taxRegime: 'NEW',
    status: 'PENDING',
    hasSalaryAssigned: false,
    complianceRuleCompliant: false,
  },
  {
    id: 'unassigned-003',
    employeeId: 'emp-108',
    employeeCode: 'EHCM-1008',
    name: 'Ananya Roy',
    department: 'Human Resources',
    designation: 'Talent Acquisition Executive',
    grade: 'G4',
    templateCode: '',
    templateName: 'No Template Assigned',
    annualCtc: 0,
    monthlyCtc: 0,
    grossSalary: 0,
    netSalary: 0,
    effectiveFrom: '',
    taxRegime: 'NEW',
    status: 'PENDING',
    hasSalaryAssigned: false,
    complianceRuleCompliant: false,
  },
];

// Indian Statutory Settings Profiles

export const INITIAL_STATUTORY_SETTINGS: StatutorySettingsData = {
  pf: {
    enabled: true,
    employeeRate: 12.0,
    employerEpfRate: 3.67,
    employerEpsRate: 8.33,
    edliRate: 0.5,
    adminRate: 0.5,
    wageCeiling: 15000,
    restrictToWageCeiling: true,
    allowVpf: true,
    autoEnrollOverCeiling: false,
  },
  esi: {
    enabled: true,
    employeeRate: 0.75,
    employerRate: 3.25,
    wageCeiling: 21000,
    disabilityWageCeiling: 25000,
  },
  professionalTax: {
    enabled: true,
    defaultState: 'MH',
    states: [
      {
        code: 'MH',
        name: 'Maharashtra',
        slabs: [
          { min: 0, max: 7500, monthlyTax: 0, febTax: 0 },
          { min: 7501, max: 10000, monthlyTax: 175, febTax: 175 },
          { min: 10001, max: 99999999, monthlyTax: 200, febTax: 300 },
        ],
      },
      {
        code: 'KA',
        name: 'Karnataka',
        slabs: [
          { min: 0, max: 24999, monthlyTax: 0 },
          { min: 25000, max: 99999999, monthlyTax: 200 },
        ],
      },
      {
        code: 'TN',
        name: 'Tamil Nadu',
        slabs: [
          { min: 0, max: 21000, monthlyTax: 0 },
          { min: 21001, max: 30000, monthlyTax: 135 },
          { min: 30001, max: 45000, monthlyTax: 315 },
          { min: 45001, max: 99999999, monthlyTax: 1025 },
        ],
      },
      {
        code: 'TS',
        name: 'Telangana',
        slabs: [
          { min: 0, max: 15000, monthlyTax: 0 },
          { min: 15001, max: 20000, monthlyTax: 150 },
          { min: 20001, max: 99999999, monthlyTax: 200 },
        ],
      },
      {
        code: 'GJ',
        name: 'Gujarat',
        slabs: [
          { min: 0, max: 12000, monthlyTax: 0 },
          { min: 12001, max: 99999999, monthlyTax: 200 },
        ],
      },
      {
        code: 'WB',
        name: 'West Bengal',
        slabs: [
          { min: 0, max: 10000, monthlyTax: 0 },
          { min: 10001, max: 15000, monthlyTax: 110 },
          { min: 15001, max: 25000, monthlyTax: 130 },
          { min: 25001, max: 40000, monthlyTax: 150 },
          { min: 40001, max: 99999999, monthlyTax: 200 },
        ],
      },
    ],
  },
  lwf: {
    enabled: true,
    states: [
      { code: 'MH', name: 'Maharashtra', frequency: 'Half-Yearly (June/Dec)', employeeShare: 12, employerShare: 36 },
      { code: 'KA', name: 'Karnataka', frequency: 'Annual (Dec)', employeeShare: 20, employerShare: 40 },
      { code: 'TN', name: 'Tamil Nadu', frequency: 'Annual (Dec)', employeeShare: 20, employerShare: 40 },
      { code: 'TS', name: 'Telangana', frequency: 'Annual (Dec)', employeeShare: 20, employerShare: 50 },
      { code: 'DL', name: 'Delhi', frequency: 'Half-Yearly (June/Dec)', employeeShare: 4.5, employerShare: 13.5 },
    ],
  },
  gratuity: {
    enabled: true,
    formulaDays: 15,
    monthDenominator: 26,
    statutoryCeiling: 2000000,
    minYearsRequired: 5,
  },
  minimumWages: [
    { state: 'Maharashtra (Zone 1)', unskilled: 13580, semiSkilled: 14890, skilled: 16250, highlySkilled: 17800, lastRevised: '2025-01-01' },
    { state: 'Karnataka (Bangalore)', unskilled: 14200, semiSkilled: 15450, skilled: 16900, highlySkilled: 18500, lastRevised: '2025-04-01' },
    { state: 'Delhi (Zone A)', unskilled: 17494, semiSkilled: 19279, skilled: 21215, highlySkilled: 23100, lastRevised: '2025-04-01' },
    { state: 'Tamil Nadu', unskilled: 12800, semiSkilled: 13900, skilled: 15200, highlySkilled: 16700, lastRevised: '2025-01-01' },
  ],
};

// Tax Slabs (Old vs New Regimes for FY 2025-26 & FY 2026-27)

export const TAX_REGIMES_CONFIG: Record<string, TaxRegimeData> = {
  '2025-2026': {
    fy: '2025-2026',
    newRegime: {
      standardDeduction: 75000,
      rebate87ALimit: 700000,
      cessRate: 4,
      slabs: [
        { min: 0, max: 300000, rate: 0 },
        { min: 300001, max: 700000, rate: 5 },
        { min: 700001, max: 1000000, rate: 10 },
        { min: 1000001, max: 1200000, rate: 15 },
        { min: 1200001, max: 1500000, rate: 20 },
        { min: 1500001, max: 99999999, rate: 30 },
      ],
    },
    oldRegime: {
      standardDeduction: 50000,
      rebate87ALimit: 500000,
      sec80CLimit: 150000,
      sec80DLimit: 25000,
      cessRate: 4,
      slabs: [
        { min: 0, max: 250000, rate: 0 },
        { min: 250001, max: 500000, rate: 5 },
        { min: 500001, max: 1000000, rate: 20 },
        { min: 1000001, max: 99999999, rate: 30 },
      ],
    },
  },
  '2026-2027': {
    fy: '2026-2027',
    newRegime: {
      standardDeduction: 75000,
      rebate87ALimit: 775000,
      cessRate: 4,
      slabs: [
        { min: 0, max: 400000, rate: 0 },
        { min: 400001, max: 800000, rate: 5 },
        { min: 800001, max: 1200000, rate: 10 },
        { min: 1200001, max: 1600000, rate: 15 },
        { min: 1600001, max: 2000000, rate: 20 },
        { min: 2000001, max: 99999999, rate: 30 },
      ],
    },
    oldRegime: {
      standardDeduction: 50000,
      rebate87ALimit: 500000,
      sec80CLimit: 150000,
      sec80DLimit: 25000,
      cessRate: 4,
      slabs: [
        { min: 0, max: 250000, rate: 0 },
        { min: 250001, max: 500000, rate: 5 },
        { min: 500001, max: 1000000, rate: 20 },
        { min: 1000001, max: 99999999, rate: 30 },
      ],
    },
  },
};
