/**
 * Canonical list of the 20 EHCM modules from the PRD, used to drive the sidebar nav
 * contract, permission seeding, and the stub module controllers.
 */
export const HCM_MODULES = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    path: 'dashboard',
    phase: 1,
    status: 'active',
  },
  {
    key: 'organization',
    label: 'Organization',
    path: 'organization',
    phase: 1,
    status: 'active',
  },
  {
    key: 'recruitment',
    label: 'Recruitment',
    path: 'recruitment',
    phase: 2,
    status: 'active',
  },
  {
    key: 'employees',
    label: 'Employee Management',
    path: 'employees',
    phase: 2,
    status: 'active',
  },
  {
    key: 'workforce',
    label: 'Workforce Management',
    path: 'workforce',
    phase: 3,
    status: 'active',
  },
  {
    key: 'attendance-leave',
    label: 'Attendance & Leave',
    path: 'attendance-leave',
    phase: 3,
    status: 'active',
  },
  {
    key: 'payroll',
    label: 'Payroll',
    path: 'payroll',
    phase: 4,
    status: 'stub',
  },
  {
    key: 'compliance',
    label: 'Compliance',
    path: 'compliance',
    phase: 4,
    status: 'stub',
  },
  {
    key: 'performance',
    label: 'Performance',
    path: 'performance',
    phase: 5,
    status: 'stub',
  },
  {
    key: 'learning',
    label: 'Learning',
    path: 'learning',
    phase: 5,
    status: 'stub',
  },
  {
    key: 'compensation-benefits',
    label: 'Compensation & Benefits',
    path: 'compensation-benefits',
    phase: 5,
    status: 'stub',
  },
  {
    key: 'employee-experience',
    label: 'Employee Experience',
    path: 'employee-experience',
    phase: 5,
    status: 'stub',
  },
  {
    key: 'asset-management',
    label: 'Asset Management',
    path: 'asset-management',
    phase: 3,
    status: 'stub',
  },
  {
    key: 'travel-expense',
    label: 'Travel & Expense',
    path: 'travel-expense',
    phase: 5,
    status: 'stub',
  },
  {
    key: 'ehs',
    label: 'Health, Safety & EHS',
    path: 'ehs',
    phase: 3,
    status: 'stub',
  },
  {
    key: 'ai-intelligence',
    label: 'AI Intelligence',
    path: 'ai-intelligence',
    phase: 6,
    status: 'stub',
  },
  {
    key: 'iot-devices',
    label: 'IoT & Smart Devices',
    path: 'iot-devices',
    phase: 6,
    status: 'stub',
  },
  {
    key: 'reports-analytics',
    label: 'Reports & Analytics',
    path: 'reports-analytics',
    phase: 7,
    status: 'stub',
  },
  {
    key: 'workflow-automation',
    label: 'Workflow & Automation',
    path: 'workflow-automation',
    phase: 1,
    status: 'stub',
  },
  {
    key: 'administration',
    label: 'Administration',
    path: 'administration',
    phase: 1,
    status: 'active',
  },
] as const;

export type HcmModuleKey = (typeof HCM_MODULES)[number]['key'];
