export interface ErpModuleDefinition {
  key: string;
  name: string;
  category: 'Core HR' | 'Workforce' | 'Payroll & Finance' | 'Compliance' | 'Talent & Learning' | 'Operations & Platform';
  description: string;
  icon: string;
  defaultPricePerMonth: number;
  features: string[];
}

export const ERP_25_MODULE_CATALOG: ErpModuleDefinition[] = [
  // ── 1. CORE HR ──
  {
    key: 'employee-management',
    name: 'Employee Management',
    category: 'Core HR',
    description: 'Complete employee lifecycle records, profiles, digital dossiers, and employment history.',
    icon: 'Users',
    defaultPricePerMonth: 499,
    features: [
      'Employee Directory',
      'Employee Profile',
      'Employee Documents',
      'Employment Details',
      'Employee History',
      'Employee Reports',
      'Advanced Employee Analytics',
    ],
  },
  {
    key: 'organization',
    name: 'Organization & Structure',
    category: 'Core HR',
    description: 'Multi-entity corporate structure, legal branches, cost centers, departments and designations.',
    icon: 'Building2',
    defaultPricePerMonth: 399,
    features: [
      'Org Chart Visualization',
      'Multi-Branch Management',
      'Department Hierarchy',
      'Designations & Grades',
      'Cost Center Allocation',
      'Company HR Policies',
    ],
  },
  {
    key: 'recruitment',
    name: 'Recruitment (ATS)',
    category: 'Core HR',
    description: 'Job requisition workflow, candidate pipeline tracking, resume parsing, and interview scheduling.',
    icon: 'UserPlus',
    defaultPricePerMonth: 699,
    features: [
      'Job Requisitions',
      'Job Openings & Job Boards',
      'Applicant Tracking Pipeline',
      'Resume AI Parser',
      'Online Candidate Assessments',
      'Interview Scheduling & MS Teams Integration',
      'Offer Letters Generation',
    ],
  },
  {
    key: 'onboarding',
    name: 'Onboarding & Induction',
    category: 'Core HR',
    description: 'New hire pre-boarding, welcome tasks, document collection, and provisioning workflows.',
    icon: 'Sparkles',
    defaultPricePerMonth: 299,
    features: [
      'Onboarding Checklists',
      'Digital Welcome Wizard',
      'Document Verification & Upload',
      'IT Asset & Seat Provisioning',
    ],
  },

  // ── 2. WORKFORCE ──
  {
    key: 'attendance-leave',
    name: 'Attendance & Leave',
    category: 'Workforce',
    description: 'Live punch tracking, biometric sync, geo-fenced mobile punches, leave policies and accruals.',
    icon: 'Clock',
    defaultPricePerMonth: 499,
    features: [
      'Live Attendance Dashboard',
      'Biometric & Geofencing Sync',
      'Leave Policy & Balance Accrual',
      'Leave Applications & Workflow',
      'Holiday Calendars',
      'Overtime Calculation',
    ],
  },
  {
    key: 'shift-planning',
    name: 'Shift & Roster Planning',
    category: 'Workforce',
    description: 'Dynamic rotational shift schedules, department rosters, shift swaps, and break rules.',
    icon: 'CalendarClock',
    defaultPricePerMonth: 399,
    features: [
      'Shift Master Setup',
      'Shift Rosters & Calendars',
      'Shift Swapping Requests',
      'Rotational Shift Engine',
    ],
  },
  {
    key: 'workforce-planning',
    name: 'Workforce Planning',
    category: 'Workforce',
    description: 'Headcount forecasting, departmental staffing budgets, and workforce capacity models.',
    icon: 'LineChart',
    defaultPricePerMonth: 499,
    features: [
      'Headcount Forecasting',
      'Department Capacity Planning',
      'Attrition Modeling',
      'Workforce Budgeting',
    ],
  },
  {
    key: 'machine-allocation',
    name: 'Machine Allocation',
    category: 'Workforce',
    description: 'Shopfloor operator assignment, machine station mapping, and production shift logs.',
    icon: 'Cpu',
    defaultPricePerMonth: 399,
    features: [
      'Machine Operator Mapping',
      'Line Balancing',
      'Skill-to-Machine Matrix',
      'Production Shift Log',
    ],
  },
  {
    key: 'contractor-management',
    name: 'Contractor Management',
    category: 'Workforce',
    description: 'Third-party labour contractor tracking, gate pass security, and compliance verification.',
    icon: 'Briefcase',
    defaultPricePerMonth: 399,
    features: [
      'Contractor Master',
      'Agency Billing Verification',
      'Contract Labour Attendance',
      'Compliance Gate Pass',
    ],
  },

  // ── 3. PAYROLL & FINANCE ──
  {
    key: 'payroll',
    name: 'Payroll Processing',
    category: 'Payroll & Finance',
    description: 'Automated gross-to-net salary runs, statutory deductions, bank transfer advice, and tax calculation.',
    icon: 'Receipt',
    defaultPricePerMonth: 999,
    features: [
      'Salary Structure Configurator',
      'Monthly Payroll Run Engine',
      'Arrears & Deduction Processing',
      'Bank Transfer File Generation (NEFT/RTGS)',
      'Tax Deduction at Source (TDS)',
    ],
  },
  {
    key: 'salary-revision',
    name: 'Salary Revision',
    category: 'Payroll & Finance',
    description: 'Appraisal increments, CTC revisions, band adjustments, and revision letter automation.',
    icon: 'TrendingUp',
    defaultPricePerMonth: 349,
    features: [
      'Increment Cycles',
      'Band Revision Matrix',
      'Promotion Letters & Revision History',
      'Compensation Benchmarking',
    ],
  },
  {
    key: 'loans-advances',
    name: 'Loans & Advances',
    category: 'Payroll & Finance',
    description: 'Employee loan requests, EMI amortization schedules, and automated payroll deductions.',
    icon: 'CreditCard',
    defaultPricePerMonth: 299,
    features: [
      'Loan Application & Approval',
      'Auto-EMI Salary Deductions',
      'Principal vs Interest Ledger',
      'Loan Foreclosure',
    ],
  },
  {
    key: 'reimbursements',
    name: 'Expense Reimbursements',
    category: 'Payroll & Finance',
    description: 'Employee claims submission, receipt scanning, managerial approvals, and payroll payout sync.',
    icon: 'ReceiptText',
    defaultPricePerMonth: 349,
    features: [
      'Expense Claim Submissions',
      'Receipt OCR Scan',
      'Multi-Level Approval Matrix',
      'Payroll Claim Payout',
    ],
  },
  {
    key: 'payslips',
    name: 'Digital Payslips',
    category: 'Payroll & Finance',
    description: 'Digitally signed password-protected payslips, ESS download, and automated email distribution.',
    icon: 'FileText',
    defaultPricePerMonth: 249,
    features: [
      'Password-Protected PDF Generation',
      'Employee Self-Service Download',
      'Bulk Email Dispatch',
      'Salary Register Sheets',
    ],
  },

  // ── 4. COMPLIANCE ──
  {
    key: 'pf-esic',
    name: 'PF & ESIC Compliance',
    category: 'Compliance',
    description: 'EPFO monthly return ECR generation, ESIC contribution filing, and statutory challan reconciliation.',
    icon: 'ShieldCheck',
    defaultPricePerMonth: 449,
    features: [
      'EPFO Monthly ECR Generation',
      'ESIC Return Filing Portal',
      'Monthly Contribution Registers',
      'Challan Verification',
    ],
  },
  {
    key: 'statutory-taxes',
    name: 'Professional Tax & TDS',
    category: 'Compliance',
    description: 'State-wise Professional Tax calculation, TDS Form 16 generation, and 24Q reporting.',
    icon: 'Landmark',
    defaultPricePerMonth: 399,
    features: [
      'State-Wise PT Slabs',
      'Income Tax Computation (Old/New Regime)',
      'Form 16 Generation',
      'Quarterly TDS 24Q Filing',
    ],
  },
  {
    key: 'labour-compliance',
    name: 'Labour Compliance & Audits',
    category: 'Compliance',
    description: 'Factory Act registers, minimum wage rate validation, bonus act records, and audit inspection logs.',
    icon: 'FileCheck',
    defaultPricePerMonth: 349,
    features: [
      'Factory Act Registers',
      'Minimum Wages Tracker',
      'Shop & Establishment Compliance',
      'Audit Trail Reports',
    ],
  },

  // ── 5. TALENT & LEARNING ──
  {
    key: 'performance',
    name: 'Performance (KPI / OKR)',
    category: 'Talent & Learning',
    description: 'Objective & Key Results (OKR), 360-degree feedback reviews, competency assessment, and 9-box grid.',
    icon: 'Target',
    defaultPricePerMonth: 599,
    features: [
      'Goal Cascading (KPI/KRA/OKR)',
      '360-Degree Appraisal Reviews',
      'Continuous Feedback Check-ins',
      'Competency Framework',
      '9-Box Succession Planning',
    ],
  },
  {
    key: 'learning',
    name: 'Learning (LMS)',
    category: 'Talent & Learning',
    description: 'Corporate training programs, external course requests, seat purchases, certificates, and skills.',
    icon: 'GraduationCap',
    defaultPricePerMonth: 799,
    features: [
      'Course Catalog & Marketplace',
      'Training Program Batches',
      'Employee Course Requests',
      'Course Purchase & Seat Allocation',
      'Certifications & Badges',
      'Skill Matrix Assessment',
    ],
  },
  {
    key: 'employee-experience',
    name: 'Employee Experience (ESS)',
    category: 'Talent & Learning',
    description: 'Self-service portal, pulse sentiment surveys, peer kudos rewards, announcements, and HR helpdesk.',
    icon: 'Smile',
    defaultPricePerMonth: 399,
    features: [
      'Employee Self Service (ESS)',
      'Manager Self Service (MSS)',
      'Pulse Surveys & Polls',
      'Peer Recognition & Rewards',
      'Internal Company Announcements',
      'HR Helpdesk & Ticketing',
    ],
  },

  // ── 6. OPERATIONS & PLATFORM ──
  {
    key: 'asset-management',
    name: 'Asset Management',
    category: 'Operations & Platform',
    description: 'Fixed asset registry, hardware/software assignment, return logistics, and maintenance depreciation.',
    icon: 'Boxes',
    defaultPricePerMonth: 449,
    features: [
      'Hardware & Software Asset Master',
      'Asset Allocation & Handover',
      'Return & Decommissioning',
      'Maintenance & Repair Tracking',
      'Depreciation Calculator',
    ],
  },
  {
    key: 'travel-expense',
    name: 'Travel & Expense',
    category: 'Operations & Platform',
    description: 'Business travel bookings, per-diem policy allowances, mileage claims, and multi-currency expense.',
    icon: 'Plane',
    defaultPricePerMonth: 449,
    features: [
      'Travel Desk Bookings',
      'Travel Request Approvals',
      'Per Diem & Daily Allowances',
      'Expense Claim Processing',
      'Multi-Currency Claims',
    ],
  },
  {
    key: 'safety-ehs',
    name: 'Safety & EHS',
    category: 'Operations & Platform',
    description: 'Workplace safety incident reporting, PPE issuance tracking, safety training, and OSHA audits.',
    icon: 'HeartPulse',
    defaultPricePerMonth: 349,
    features: [
      'PPE Distribution & Inventory',
      'Workplace Incident Reporting',
      'Safety Training Records',
      'OSHA & ISO Audits',
      'Hazard Risk Registry',
    ],
  },
  {
    key: 'ai-intelligence',
    name: 'AI Intelligence Center',
    category: 'Operations & Platform',
    description: 'AI resume ranking, attendance anomaly detection, predictive churn alerts, and HR assistant chatbot.',
    icon: 'Sparkles',
    defaultPricePerMonth: 899,
    features: [
      'Recruitment Resume Ranker AI',
      'Attendance Anomaly Detector',
      'Payroll Audit & Anomaly Engine',
      'HR Conversational Assistant',
      'Predictive Employee Churn Analytics',
    ],
  },
  {
    key: 'integrations-iot',
    name: 'IoT & ERP Integrations',
    category: 'Operations & Platform',
    description: 'Biometric device gateway, SAP/Tally accounting connectors, REST API tokens, and webhooks.',
    icon: 'Network',
    defaultPricePerMonth: 699,
    features: [
      'Biometric & Face Terminal Connectors',
      'Real-Time Telemetry Logs',
      'ERP Connectors (SAP/Oracle)',
      'Accounting Sync (Tally/Zoho)',
      'REST API & Webhooks Engine',
    ],
  },
];
