import type {
  PayrollRunItem,
  PreRunCheckItem,
  AttendanceLopRecord,
  VariableInputRecord,
  EmployeePayrollReviewRecord,
  FnfSettlementRecord,
} from './types';

export * from './types';

// Runtime export fallbacks for bundlers
export const PayrollRunItem = undefined;
export const PreRunCheckItem = undefined;
export const AttendanceLopRecord = undefined;
export const VariableInputRecord = undefined;
export const EmployeePayrollReviewRecord = undefined;
export const FnfSettlementRecord = undefined;

export const SAMPLE_PAYROLL_RUNS: PayrollRunItem[] = [
  {
    id: 'run-sep-2026',
    runCode: 'PR-2026-09',
    month: 9,
    monthName: 'September',
    year: 2026,
    runType: 'REGULAR',
    title: 'Regular Monthly Payroll - September 2026',
    status: 'CALCULATED',
    headcount: 5,
    totalGross: 452100,
    totalDeductions: 41200,
    totalNet: 410900,
    totalEmployerCost: 494500,
    calculatedAt: '2026-09-24T10:30:00Z',
    calculatedBy: 'ppurvesh503 (Payroll Admin)',
  },
  {
    id: 'run-aug-2026',
    runCode: 'PR-2026-08',
    month: 8,
    monthName: 'August',
    year: 2026,
    runType: 'REGULAR',
    title: 'Regular Monthly Payroll - August 2026',
    status: 'PAID',
    headcount: 5,
    totalGross: 442500,
    totalDeductions: 39800,
    totalNet: 402700,
    totalEmployerCost: 483200,
    calculatedAt: '2026-08-28T09:00:00Z',
    calculatedBy: 'ppurvesh503 (Payroll Admin)',
    approvedAt: '2026-08-29T14:15:00Z',
    approvedBy: 'Finance Director',
    lockedAt: '2026-08-30T10:00:00Z',
    lockedBy: 'ppurvesh503',
    paidAt: '2026-08-31T16:00:00Z',
    paidBy: 'HDFC Corporate Portal',
    isBankTransferDone: true,
  },
  {
    id: 'run-diwali-2026',
    runCode: 'PR-OFF-2026-1',
    month: 9,
    monthName: 'September',
    year: 2026,
    runType: 'OFF_CYCLE',
    title: 'Festive Bonus & Annual Incentive Payout',
    status: 'DRAFT',
    headcount: 5,
    totalGross: 125000,
    totalDeductions: 12500,
    totalNet: 112500,
    totalEmployerCost: 125000,
  },
  {
    id: 'run-fnf-sep-2026',
    runCode: 'PR-FNF-2026-09',
    month: 9,
    monthName: 'September',
    year: 2026,
    runType: 'FNF',
    title: 'Full & Final Settlement - Amit Verma (Exit)',
    status: 'APPROVED',
    headcount: 1,
    totalGross: 84500,
    totalDeductions: 14200,
    totalNet: 70300,
    totalEmployerCost: 84500,
    approvedAt: '2026-09-22T11:00:00Z',
    approvedBy: 'HR Head',
  },
];

export const SAMPLE_PRE_RUN_CHECKLIST: PreRunCheckItem[] = [
  {
    id: 'chk-01',
    category: 'SALARY',
    severity: 'CRITICAL',
    title: 'Employees Missing Salary Structure',
    description: 'Employees who do not have an active compensation template assigned will be omitted from computation.',
    affectedCount: 2,
    affectedEmployees: [
      { id: 'emp-106', name: 'Kavita Joshi', code: 'EHCM-1006', detail: 'QA Automation Engineer - No Template' },
      { id: 'emp-107', name: 'Vikram Singh', code: 'EHCM-1007', detail: 'Warehouse Coordinator - No Template' },
    ],
    isResolved: false,
  },
  {
    id: 'chk-02',
    category: 'BANK',
    severity: 'WARNING',
    title: 'Employees Missing Bank Account / IFSC',
    description: 'Direct bank transfer batch generation will fail for employees without verified banking details.',
    affectedCount: 1,
    affectedEmployees: [
      { id: 'emp-108', name: 'Ananya Roy', code: 'EHCM-1008', detail: 'Account Number Missing' },
    ],
    isResolved: false,
  },
  {
    id: 'chk-03',
    category: 'PAN',
    severity: 'WARNING',
    title: 'Missing PAN (Subject to 20% Higher TDS)',
    description: 'Under Section 206AA, non-furnishing of PAN mandates deduction at 20% or maximum marginal rate.',
    affectedCount: 1,
    affectedEmployees: [
      { id: 'emp-105', name: 'Rohan Verma', code: 'EHCM-1005', detail: 'PAN Verification Pending' },
    ],
    isResolved: false,
  },
  {
    id: 'chk-04',
    category: 'ATTENDANCE',
    severity: 'INFO',
    title: 'Attendance & Leave Finalization',
    description: 'Attendance records for September 2026 are fully synced from Biometric and Attendance module.',
    affectedCount: 0,
    affectedEmployees: [],
    isResolved: true,
  },
  {
    id: 'chk-05',
    category: 'EMPLOYEE',
    severity: 'INFO',
    title: 'Mid-Month New Joiners & Exits',
    description: 'Pro-rata wage adjustments will automatically apply based on date of joining and exit dates.',
    affectedCount: 1,
    affectedEmployees: [
      { id: 'emp-104', name: 'Neha Deshmukh', code: 'EHCM-1004', detail: 'Joined on 15th - 16 Paid Days' },
    ],
    isResolved: true,
  },
];

export const SAMPLE_ATTENDANCE_LOP: AttendanceLopRecord[] = [
  {
    id: 'att-1',
    employeeId: 'emp-101',
    employeeCode: 'EHCM-1001',
    name: 'Sudarshan Kales',
    department: 'Engineering',
    totalCalendarDays: 30,
    payableDays: 30,
    presentDays: 22,
    paidLeaves: 0,
    lopDays: 0,
    weeklyOffs: 8,
    holidays: 0,
    attendanceFinalized: true,
    proRataFactor: 1.0,
  },
  {
    id: 'att-2',
    employeeId: 'emp-102',
    employeeCode: 'EHCM-1002',
    name: 'Priyanka Sharma',
    department: 'Product',
    totalCalendarDays: 30,
    payableDays: 28,
    presentDays: 19,
    paidLeaves: 1,
    lopDays: 2,
    weeklyOffs: 8,
    holidays: 0,
    attendanceFinalized: true,
    proRataFactor: 0.933,
  },
  {
    id: 'att-3',
    employeeId: 'emp-103',
    employeeCode: 'EHCM-1003',
    name: 'Aarav Patel',
    department: 'Operations',
    totalCalendarDays: 30,
    payableDays: 30,
    presentDays: 22,
    paidLeaves: 0,
    lopDays: 0,
    weeklyOffs: 8,
    holidays: 0,
    attendanceFinalized: true,
    proRataFactor: 1.0,
  },
  {
    id: 'att-4',
    employeeId: 'emp-104',
    employeeCode: 'EHCM-1004',
    name: 'Neha Deshmukh',
    department: 'Healthcare',
    totalCalendarDays: 30,
    payableDays: 16,
    presentDays: 12,
    paidLeaves: 0,
    lopDays: 0,
    weeklyOffs: 4,
    holidays: 0,
    attendanceFinalized: true,
    proRataFactor: 0.533, // Joined mid-month
  },
  {
    id: 'att-5',
    employeeId: 'emp-105',
    employeeCode: 'EHCM-1005',
    name: 'Rohan Verma',
    department: 'Retail Sales',
    totalCalendarDays: 30,
    payableDays: 29,
    presentDays: 21,
    paidLeaves: 0,
    lopDays: 1,
    weeklyOffs: 8,
    holidays: 0,
    attendanceFinalized: true,
    proRataFactor: 0.967,
  },
];

export const SAMPLE_VARIABLE_INPUTS: VariableInputRecord[] = [
  {
    id: 'var-1',
    employeeId: 'emp-101',
    employeeCode: 'EHCM-1001',
    name: 'Sudarshan Kales',
    department: 'Engineering',
    overtimeHours: 0,
    overtimeAmount: 0,
    performanceBonus: 15000,
    salesIncentive: 0,
    revisionArrears: 0,
    oneTimeEarnings: 0,
    oneTimeDeductions: 0,
    loanEmiDeduction: 0,
    reimbursementPayout: 3900,
  },
  {
    id: 'var-2',
    employeeId: 'emp-102',
    employeeCode: 'EHCM-1002',
    name: 'Priyanka Sharma',
    department: 'Product',
    overtimeHours: 0,
    overtimeAmount: 0,
    performanceBonus: 0,
    salesIncentive: 0,
    revisionArrears: 4500,
    oneTimeEarnings: 0,
    oneTimeDeductions: 0,
    loanEmiDeduction: 5000,
    reimbursementPayout: 2100,
  },
  {
    id: 'var-3',
    employeeId: 'emp-103',
    employeeCode: 'EHCM-1003',
    name: 'Aarav Patel',
    department: 'Operations',
    overtimeHours: 16,
    overtimeAmount: 4615,
    performanceBonus: 0,
    salesIncentive: 2000,
    revisionArrears: 0,
    oneTimeEarnings: 0,
    oneTimeDeductions: 0,
    loanEmiDeduction: 2500,
    reimbursementPayout: 0,
  },
  {
    id: 'var-4',
    employeeId: 'emp-104',
    employeeCode: 'EHCM-1004',
    name: 'Neha Deshmukh',
    department: 'Healthcare',
    overtimeHours: 8,
    overtimeAmount: 2600,
    performanceBonus: 0,
    salesIncentive: 0,
    revisionArrears: 0,
    oneTimeEarnings: 0,
    oneTimeDeductions: 0,
    loanEmiDeduction: 0,
    reimbursementPayout: 0,
  },
  {
    id: 'var-5',
    employeeId: 'emp-105',
    employeeCode: 'EHCM-1005',
    name: 'Rohan Verma',
    department: 'Retail Sales',
    overtimeHours: 0,
    overtimeAmount: 0,
    performanceBonus: 0,
    salesIncentive: 5500,
    revisionArrears: 0,
    oneTimeEarnings: 0,
    oneTimeDeductions: 500,
    loanEmiDeduction: 0,
    reimbursementPayout: 0,
  },
];

export const SAMPLE_REVIEW_RECORDS: EmployeePayrollReviewRecord[] = [
  {
    id: 'rev-1',
    employeeId: 'emp-101',
    employeeCode: 'EHCM-1001',
    name: 'Sudarshan Kales',
    department: 'Engineering',
    designation: 'Staff Software Architect',
    grade: 'G1',
    panNumber: 'ABCDE1234F',
    bankAccount: 'HDFC •••• 8912',
    templateCode: 'IT-ENG-CTC',
    annualCtc: 2400000,
    monthlyCtc: 200000,
    paidDays: 30,
    lopDays: 0,
    basicSalary: 100000,
    hra: 50000,
    allowances: 41600,
    grossPay: 191600,
    employeePf: 1800,
    employeeEsi: 0,
    professionalTax: 200,
    tds: 16800,
    loanEmi: 0,
    otherDeductions: 0,
    totalDeductions: 18800,
    netPay: 172800,
    employerPf: 1800,
    employerEsi: 0,
    employerGratuity: 4808,
    totalEmployerCost: 198208,
    previousMonthNet: 172800,
    varianceAmount: 0,
    variancePercentage: 0,
    hasException: false,
    isSalaryHeld: false,
  },
  {
    id: 'rev-2',
    employeeId: 'emp-102',
    employeeCode: 'EHCM-1002',
    name: 'Priyanka Sharma',
    department: 'Product',
    designation: 'Senior Product Manager',
    grade: 'G2',
    panNumber: 'FGHIJ5678K',
    bankAccount: 'ICICI •••• 4421',
    templateCode: 'IT-ENG-CTC',
    annualCtc: 1800000,
    monthlyCtc: 150000,
    paidDays: 28,
    lopDays: 2,
    basicSalary: 70000,
    hra: 35000,
    allowances: 29120, // Pro-rated for 28 days
    grossPay: 134120,
    employeePf: 1800,
    employeeEsi: 0,
    professionalTax: 200,
    tds: 9500,
    loanEmi: 5000,
    otherDeductions: 0,
    totalDeductions: 16500,
    netPay: 117620,
    employerPf: 1800,
    employerEsi: 0,
    employerGratuity: 3365,
    totalEmployerCost: 139285,
    previousMonthNet: 129500,
    varianceAmount: -11880,
    variancePercentage: -9.2,
    hasException: false,
    isSalaryHeld: false,
  },
  {
    id: 'rev-3',
    employeeId: 'emp-103',
    employeeCode: 'EHCM-1003',
    name: 'Aarav Patel',
    department: 'Operations',
    designation: 'Plant Floor Supervisor',
    grade: 'L4',
    panNumber: 'KLMNO9012P',
    bankAccount: 'SBI •••• 1102',
    templateCode: 'MFG-FLOOR-WAGE',
    annualCtc: 480000,
    monthlyCtc: 40000,
    paidDays: 30,
    lopDays: 0,
    basicSalary: 22000,
    hra: 8800,
    allowances: 11415, // includes OT ₹4,615 & Incentive ₹2,000
    grossPay: 42215,
    employeePf: 1800,
    employeeEsi: 0,
    professionalTax: 200,
    tds: 0,
    loanEmi: 2500,
    otherDeductions: 12,
    totalDeductions: 4512,
    netPay: 37703,
    employerPf: 1800,
    employerEsi: 0,
    employerGratuity: 1058,
    totalEmployerCost: 45073,
    previousMonthNet: 34800,
    varianceAmount: 2903,
    variancePercentage: 8.3,
    hasException: false,
    isSalaryHeld: false,
  },
  {
    id: 'rev-4',
    employeeId: 'emp-104',
    employeeCode: 'EHCM-1004',
    name: 'Neha Deshmukh',
    department: 'Healthcare',
    designation: 'Senior Staff Nurse',
    grade: 'G4',
    panNumber: 'PQRST3456U',
    bankAccount: 'AXIS •••• 7723',
    templateCode: 'HEALTH-CLINICAL-NURSE',
    annualCtc: 650000,
    monthlyCtc: 54167,
    paidDays: 16,
    lopDays: 0,
    basicSalary: 14400, // Pro-rated for 16 days
    hra: 5760,
    allowances: 9740, // includes OT ₹2,600
    grossPay: 29900,
    employeePf: 1728,
    employeeEsi: 0,
    professionalTax: 200,
    tds: 0,
    loanEmi: 0,
    otherDeductions: 0,
    totalDeductions: 1928,
    netPay: 27972,
    employerPf: 1728,
    employerEsi: 0,
    employerGratuity: 693,
    totalEmployerCost: 32321,
    previousMonthNet: 0,
    varianceAmount: 27972,
    variancePercentage: 100,
    hasException: true,
    exceptionReason: 'New Joiner in current cycle (16 paid days)',
    isSalaryHeld: false,
  },
  {
    id: 'rev-5',
    employeeId: 'emp-105',
    employeeCode: 'EHCM-1005',
    name: 'Rohan Verma',
    department: 'Retail Sales',
    designation: 'Store Lead Associate',
    grade: 'L4',
    panNumber: 'UVWXY7890Z',
    bankAccount: 'KOTAK •••• 5590',
    templateCode: 'RETAIL-STORE-ASSOC',
    annualCtc: 360000,
    monthlyCtc: 30000,
    paidDays: 29,
    lopDays: 1,
    basicSalary: 14500,
    hra: 5800,
    allowances: 13600, // includes incentive ₹5,500
    grossPay: 33900,
    employeePf: 1740,
    employeeEsi: 0,
    professionalTax: 200,
    tds: 0,
    loanEmi: 0,
    otherDeductions: 512,
    totalDeductions: 2452,
    netPay: 31448,
    employerPf: 1740,
    employerEsi: 0,
    employerGratuity: 698,
    totalEmployerCost: 36338,
    previousMonthNet: 26200,
    varianceAmount: 5248,
    variancePercentage: 20.0,
    hasException: true,
    exceptionReason: 'High sales incentive (+20% variance)',
    isSalaryHeld: false,
  },
];

export const SAMPLE_FNF_RECORDS: FnfSettlementRecord[] = [
  {
    id: 'fnf-01',
    employeeId: 'emp-109',
    employeeCode: 'EHCM-1009',
    name: 'Amit Verma',
    department: 'Engineering',
    designation: 'Senior Frontend Engineer',
    joiningDate: '2021-03-15',
    resignationDate: '2026-08-15',
    lastWorkingDay: '2026-09-15',
    noticePeriodRequiredDays: 90,
    noticePeriodServedDays: 31,
    shortfallDays: 59,
    proRatedSalary: 42500, // 15 days in September
    leaveEncashmentDays: 18,
    leaveEncashmentAmount: 32000,
    noticePayRecoveryAmount: 0, // Waived by Management
    gratuityAmount: 78500, // Completed 5.5 years (15 * Basic * 5 / 26)
    bonusAmount: 12000,
    outstandingLoanBalance: 0,
    finalTds: 14700,
    totalEarnings: 165000,
    totalRecoveries: 14700,
    netSettlementPayable: 150300,
    settlementStatus: 'APPROVED',
    paymentMode: 'NEFT',
  },
];
